-- Script de Base de Datos para Gestor de Pruebas de Usabilidad (Supabase - PostgreSQL)
-- Cópialo y pégalo en el SQL Editor de Supabase y dale a "RUN".

-- 1. Tabla de Proyectos
CREATE TABLE proyectos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  descripcion TEXT,
  fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de Planes de Prueba (1 a 1 con Proyecto)
CREATE TABLE planes_prueba (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id BIGINT NOT NULL REFERENCES proyectos(id) ON DELETE CASCADE,
  producto VARCHAR(255),
  pantalla VARCHAR(255),
  objetivo TEXT,
  perfil VARCHAR(255),
  metodo VARCHAR(100),
  fecha DATE,
  lugar VARCHAR(255),
  duracion VARCHAR(100),
  moderador VARCHAR(255),
  observador VARCHAR(255),
  herramienta VARCHAR(255),
  enlace VARCHAR(500),
  notas TEXT
);

-- 3. Tabla de Tareas del Plan
CREATE TABLE tareas_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id BIGINT NOT NULL REFERENCES proyectos(id) ON DELETE CASCADE,
  identificador VARCHAR(10) NOT NULL,
  escenario TEXT,
  resultado_esperado TEXT,
  metrica_principal VARCHAR(255),
  criterio_exito TEXT
);

-- 3.5. Tabla de Tareas del Guion
CREATE TABLE tareas_guion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id BIGINT NOT NULL REFERENCES proyectos(id) ON DELETE CASCADE,
  identificador VARCHAR(10) NOT NULL,
  texto TEXT,
  pregunta TEXT,
  exito_esperado TEXT
);

-- 4. Tabla de Observaciones
CREATE TABLE observaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id BIGINT NOT NULL REFERENCES proyectos(id) ON DELETE CASCADE,
  participante VARCHAR(255),
  perfil VARCHAR(255),
  tarea_id VARCHAR(10),
  exito VARCHAR(100),
  tiempo VARCHAR(50),
  errores VARCHAR(50),
  comentarios TEXT,
  problema TEXT,
  severidad VARCHAR(50) DEFAULT 'Baja',
  mejora TEXT
);

-- 5. Tabla de Hallazgos
CREATE TABLE hallazgos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  proyecto_id BIGINT NOT NULL REFERENCES proyectos(id) ON DELETE CASCADE,
  problema TEXT NOT NULL,
  evidencia TEXT,
  frecuencia VARCHAR(50), 
  severidad VARCHAR(50) DEFAULT 'Media',
  recomendacion TEXT,
  prioridad VARCHAR(50),
  estado VARCHAR(50)
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE proyectos ENABLE ROW LEVEL SECURITY;
ALTER TABLE planes_prueba ENABLE ROW LEVEL SECURITY;
ALTER TABLE tareas_plan ENABLE ROW LEVEL SECURITY;
ALTER TABLE tareas_guion ENABLE ROW LEVEL SECURITY;
ALTER TABLE observaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE hallazgos ENABLE ROW LEVEL SECURITY;

-- Políticas para permitir acceso público (Replica el comportamiento de Express sin Auth)
CREATE POLICY "Public Access" ON proyectos FOR ALL USING (true);
CREATE POLICY "Public Access" ON planes_prueba FOR ALL USING (true);
CREATE POLICY "Public Access" ON tareas_plan FOR ALL USING (true);
CREATE POLICY "Public Access" ON tareas_guion FOR ALL USING (true);
CREATE POLICY "Public Access" ON observaciones FOR ALL USING (true);
CREATE POLICY "Public Access" ON hallazgos FOR ALL USING (true);
